# Generated by Django 4.2.23 on 2025-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews_count',
            new_name='review_count',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Оригинальная цена товара без скидки', max_digits=10, verbose_name='Оригинальная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_id',
            field=models.BigIntegerField(default=0, help_text='Уникальный идентификатор товара на Wildberries', unique=True, verbose_name='ID товара на Wildberries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Текущая цена товара (со скидкой)', max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
    ]
